### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. How to fix it?

### ISSUE THREAD

**Issue by My12123** [msxie92/MangaInpainting#10]
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject. How to fix it?
![2022-09-13_16-20-22](https://user-images.githubusercontent.com/49092250/189912438-e3f49a4f-75f0-4c9f-b4be-89818f4cf069.png)

**Comment by Neutronoid** [comment]
Make sure to uninstall the current Numpy and install numpy-1.19.5
