### ISSUE TITLE
Question about lines image

### ISSUE THREAD

**Issue by Sanster** [msxie92/MangaInpainting#12]
Hi, I'm trying to add MangaInpainting in the inpainting tool [Lama Cleaner](https://github.com/Sanster/lama-cleaner). I noticed the image of the lines get from [MangaLineExtraction_PyTorch](https://github.com/ljsabc/MangaLineExtraction_PyTorch) is different from the image of the lines in this repo. Do you use a custom-trained lines extract model to get the result?

|line image in this repo|  result of [MangaLineExtraction_PyTorch](https://github.com/ljsabc/MangaLineExtraction_PyTorch)|
|---------------------|-----|
|![shegreat_0020](https://user-images.githubusercontent.com/3998421/202428712-38bd9d38-091c-4f04-a640-4be930aa5129.png)|![shegreat_0020](https://user-images.githubusercontent.com/3998421/202428835-3ab1d1dc-8a22-4641-9cb6-5b572e98491b.png)|

**Comment by msxie92** [comment]
I extract the lines using their [Keras version](https://github.com/ljsabc/MangaLineExtraction) instead of the PyTorch version. Maybe you can try the previous one.

**Comment by Sanster** [comment]
Thank you, I will try it.

**Comment by msxie92** [comment]
Hi, I used [MangaLineExtraction_PyTorch](https://github.com/ljsabc/MangaLineExtraction_PyTorch) to extract the structural line, which is shown below. It is quite similar with the result extracted by Keras version. 
![representative(1)](https://user-images.githubusercontent.com/34064199/202463308-49f85ef3-93b3-4642-a505-255e94b09c05.png)

**Comment by Sanster** [comment]
Wow, thank you for trying it for me, there must be something wrong with my setup, I will check it

**Comment by msxie92** [comment]
I notice that I resize the image when it is larger than 1280. The result here is with resolution 1105x757. You can try with a smaller resolution.

**Comment by Sanster** [comment]
I can get a similar structural line result after resizing the input image to 1105x757. 

I would like to add a comparison image when making a release(Manga model support) of [Lama Cleaner](https://github.com/Sanster/lama-cleaner) to show that the Manga model works better than the [LaMa](https://github.com/saic-mdal/lama) model in this particular scenario. 

On high-resolution(1470x1010) image, Manga model generates a better result. On lower resolution(1080x740) Manga model's result looks like more artificial. 

**My question is**: Is it normal to get such results? (I have only tested on the example data, and I know it is likely that more testing will be needed to illustrate the model effects, just want to make sure I haven't missed something ) Thanks.

| Model |  1080x740  |  1470x1010 |
|--------|------------|------------|
|Manga|![manga_1080x740](https://user-images.githubusercontent.com/3998421/202676629-54f40f20-c55b-4e6d-bcc7-0a4e81fbb27d.png)|![manga_1470x1010](https://user-images.githubusercontent.com/3998421/202675839-4f8012d5-1c10-47ea-9628-20512e86f192.png)|
|[LaMa](https://github.com/saic-mdal/lama)|![lama_1080x740](https://user-images.githubusercontent.com/3998421/202675704-53fa7a3d-ec74-4044-a19c-c673d74bdd28.png)|![lama_1470x1010](https://user-images.githubusercontent.com/3998421/202675746-1e642367-f5d0-4b48-aa8b-5d82f2e29082.png)|

**Comment by msxie92** [comment]
The manga inpainting model is trained with high-quality images, it may not be able to reconstruct blurry patterns in the rescaled manga input.

**Comment by Sanster** [comment]
Added in https://github.com/Sanster/lama-cleaner/releases/tag/0.27.1

```bash
pip install lama-cleaner
# Models will be downloaded at the first time used
lama-cleaner --model=manga --device=cuda --port=8080
# Lama Cleaner is now running at http://localhost:8080
```
