### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by naoki7090624** [msxie92/MangaInpainting#4]
I tested one image using a RTX2080Ti, but I couldn't get the result due to "CUDA out of memory".

```
RuntimeError: CUDA out of memory. Tried to allocate 3.38 GiB (GPU 0; 10.76 GiB total capacity; 5.69 GiB already allocated; 2.85 GiB free; 1.31 GiB cached)
```

Can you tell me which GPUs you used and how long did it take you to train?

**Comment by msxie92** [comment]
I tested my code on TITAN Xp. For a 512x512 resolution image, it takes about 0.37 seconds to test. And 1.78 seconds at 1024x1024.

**Comment by naoki7090624** [comment]
Thank you for reply.
Did you use 4 TITAN Xp on training? How long did it take?

**Comment by msxie92** [comment]
I used 4 TITAN Xp on training. 
When training, it takes about 1 week for the semantic inpainting model, 3 days for the manga inpainting model, and 3 days for simultaneously refining the two models.
