### ISSUE TITLE
How to calculate the distance field map and confidence map

### ISSUE THREAD

**Issue by naoki7090624** [msxie92/MangaInpainting#7]
Great work!!
I have two questions about semantic inpainting.

According to your paper, the distance field map M_d and confidence map M_c are weighted according to the distance from the boundary. It seems computationally intensive to calculate the distance from the boundary of each pixel, is there an efficient way to do this?
If it's possible, would you share the code for that part?

**Comment by jerrywyn** [comment]
According to the released code, I think the structural line image and its distance field map is prepared before training, and add them  to the input. 
My question is how to calculate the confidence map. It seems that the confidence map is not like the map from that origin paper, how should I prepare it or calculate it?
Looking forward to your reply!

**Comment by msxie92** [comment]
The original distance field map can be calculated by calling 
scipy.ndimage.distance_transform_edt
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html
And the distance map is normalized by the factor of patch size.

We do different post-processing to get the two maps. 
For the distance field map M_d, we add a base value as the original distance field map will get 0 at the edge. 
For confidence map M_c, we invert the original distance field map to get decreasing weight.

**Comment by jerrywyn** [comment]
this is the output after calling scipy.ndimage.distance_transform_edt, I simply normalized it by divide the max in distance map to get 0-1 map.
It seems that it should apply a norm function? what does "And the distance map is normalized by the factor of patch size." mean? 
![003](https://user-images.githubusercontent.com/48412363/129179036-917b6fe0-fe5f-4c9a-aa52-6e110fb8f214.jpg)
![xx1](https://user-images.githubusercontent.com/48412363/129180309-14564a88-a09d-4449-8627-b8caf6319468.png)
![xx](https://user-images.githubusercontent.com/48412363/129180468-a0b50a9f-2065-4c18-a1ac-1f40e3650ba1.png)

**Comment by msxie92** [comment]
My normalized factor is sqrt(patch_size*patch_size). Simply normalize [min, max] to [0,1] map is unbalanced for different samples.

**Comment by naoki7090624** [comment]
The following images show the distance field map and confidence map generated using [example image](https://github.com/msxie92/MangaInpainting/blob/main/examples/test/lines/shegreat_0020.png) and the following code.
```
from scipy.ndimage import distance_transform_edt
from skimage import io
import math
import os

img = io.imread("lines.png",as_gray=True) / 255.0
dismap = distance_transform_edt(img) / math.sqrt(30.0*30.0) # patch size is 30*30
disfieldmap = dismap + 0.5 # add base value
M = max(disfieldmap.flatten())
confmap = M - dismap # invert distance field map
dfm = os.path.join("distanceMap","distanceFieldMap.png")
cm = os.path.join("distanceMap","confMap.png")

io.imsave(dfm,disfieldmap)
io.imsave(cm,confmap)
```

![distanceFieldMap](https://user-images.githubusercontent.com/39236999/129656425-72828b82-c621-4d02-b6ed-1b11dd3aae9f.png)
![confMap](https://user-images.githubusercontent.com/39236999/129656428-a5795a2a-b6d2-49c2-9798-8fc58e8f02d1.png)

Are these normal results?
