### ISSUE TITLE
Mask images

### ISSUE THREAD

**Issue by dahnny012** [msxie92/MangaInpainting#9]
Hello,

How are the mask images in the example/test obtained? Are they automatically generated or are you manually creating them.

**Comment by msxie92** [comment]
You can detect the text and then extract the text balloons with some postprocessing.
Liu, X., Li, C., Zhu, H., Wong, T. T., & Xu, X. (2016). Text-aware balloon extraction from manga. The Visual Computer, 32(4), 501-511.

**Comment by dahnny012** [comment]
thank you ill take a look. In the mean time i generated maps manually and i linked it up to a custom manga reader.

The results are fun. Love the research ^^

https://imgur.com/a/CgEdoSN

**Comment by msxie92** [comment]
Thanks for sharing! I'm glad you liked my work.
